### ISSUE TITLE
[FEAT] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by dpdms529** [woorifisa-projects-3rd/WeKids-BaaS#1]
# ⚙️ ISSUE
- 프로젝트 초기 세팅

# 📄 To-Do
- [x] 스프링 프로젝트 생성
- [x] .gitmessage.txt 생성
- [x] 이슈, pr 템플릿 생성
- [x] 패키지 생성
